version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "6000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./fontend
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - ./fontend/.env
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
